export const mockSliders = ["/images/slider/1.jpg", "/images/slider/2.png", "/images/slider/3.png", "/images/slider/4.webp"];

export const mockHomeCars = [
    {
        id: 1,
        name: "VF 3",
        image: "/images/homeCars/vf3.webp",
        type: "Mini SUV",
        price: "299.000.000 VNĐ (NEDC)",
        distance: "~ 210 km (NEDC)",
        slot: "4 chỗ",
        power: "32 kW",
        descript: "",
    },
    {
        id: 2,
        name: "VF 5",
        image: "/images/homeCars/vf5.webp",
        type: "A SUV",
        price: "529.000.000 VNĐ (NEDC)",
        distance: "~ 326,4 km (NEDC)",
        slot: "5 chỗ",
        power: "100 kW",
        descript: "",
    },
    {
        id: 3,
        name: "VF 6",
        image: "/images/homeCars/vf6.webp",
        type: "B SUV",
        price: "689.000.000 VNĐ (NEDC)",
        distance: "~ 480 km (NEDC)",
        slot: "5 chỗ",
        power: "150 kW",
        descript: "",
    },
    {
        id: 4,
        name: "VF 7",
        image: "/images/homeCars/vf7.webp",
        type: "C SUV",
        price: "799.000.000 VNĐ (NEDC)",
        distance: "~ 431 km (NEDC)",
        slot: "5 chỗ",
        power: "260 kW",
        descript: "",
    },
    {
        id: 5,
        name: "VF 8",
        image: "/images/homeCars/vf8.webp",
        type: "D SUV",
        price: "1.019.000.000 VNĐ (NEDC)",
        distance: "~ 471 km (NEDC)",
        slot: "5 chỗ",
        power: "300 kW",
        descript: "",
    },
    {
        id: 6,
        name: "VF 9",
        image: "/images/homeCars/vf9.webp",
        type: "E SUV",
        price: "1.499.000.000 VNĐ (NEDC)",
        distance: "~ 626 km (NEDC)",
        slot: "6-7 chỗ",
        power: "300 kW",
        descript: "",
    },
    {
        id: 7,
        name: "MINIO GREEN",
        image: "/images/homeCars/nimo.webp",
        type: "MiniCar",
        price: "269.000.000 VNĐ (NEDC)",
        distance: "~ 170 km (NEDC)",
        slot: "4 chỗ",
        power: "30 kW",
        descript: "",
    },
    {
        id: 8,
        name: "HERIO GREEN",
        image: "/images/homeCars/herio.webp",
        type: "A SUV",
        price: "499.000.000 VNĐ (NEDC)",
        distance: "~ 326 km (NEDC)",
        slot: "5 chỗ",
        power: "110 kW",
        descript: "",
    },
    {
        id: 9,
        name: "NERIO GREEN",
        image: "/images/homeCars/nerio.webp",
        type: "B SUV",
        price: "688.000.000 VNĐ (NEDC)",
        distance: "~ 318 km (NEDC)",
        slot: "5 chỗ",
        power: "140 kW",
        descript: "",
    },
    {
        id: 10,
        name: "LIMO GREEN",
        image: "/images/homeCars/limo.webp",
        type: "MPV",
        price: "749.000.000 VNĐ (NEDC)",
        distance: "~ 450 km (NEDC)",
        slot: "7 chỗ",
        power: "180 kW",
        descript: "",
    },
    {
        id: 11,
        name: "EC VAN",
        image: "/images/homeCars/ec.webp",
        type: "> 600kg",
        price: "285.000.000 VNĐ (NEDC)",
        distance: "~ 150 km (NEDC)",
        slot: "2 chỗ",
        power: "40 kW",
        descript: "",
    },
    {
        id: 12,
        name: "E BUS",
        image: "/images/homeCars/ebus.png",
        type: "Car",
        price: "2.800.000.000 VNĐ (NEDC)",
        distance: "~ 250 km (NEDC)",
        slot: "Nhiều chỗ",
        power: "200 kW",
        descript: "",
    },
];
